[package]
name = "hdp_installer"
version = "0.1.0"
edition = "2021"

include = ["bin/**"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
emojis = "0.5.1"
ping = "0.4.0"
ssh2 = "0.9.3"
